# Generated by Django 2.2.6 on 2019-10-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('main', '0003_auto_20191009_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CheckIn'),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CheckOut'),
        ),
    ]
